'use client';

// Phosphor uses React context internally, so it must cross a client boundary
// before the server-rendered landing page can use these icons.
export {
  Broadcast,
  PenNib,
  ChatCircleText,
  Lightning,
  Trophy,
  Certificate,
  Check,
  ArrowRight,
  SealCheck,
  NotePencil,
  CalendarCheck,
  UsersThree,
  Monitor,
  GraduationCap,
  BookOpenText,
  Code,
  Exam,
  ChartLineUp,
  WifiHigh,
  DeviceMobile,
  Buildings,
  ShieldCheck,
  Sparkle,
  X,
  Minus,
  Gauge,
  Quotes,
  User,
  Mosque,
  Laptop,
  CalendarBlank,
  Stack,
  Cursor,
  PencilSimple,
  Square,
  TextT,
  Play,
  SkipForward,
  Microphone,
  FileText,
  ChartBar,
  CaretRight,
} from '@phosphor-icons/react';
